name: Caravel Cocotb CI

on:
  push:
    branches:
      - main  
      - dev
      - CI_dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        cd cocotb/caravel_cocotb
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install docker
        python3 -m pip install --upgrade --no-cache-dir volare
    
    - name: Install caravel_cocotb
      run: |
        cd cocotb
        pip install .

    - name: Run main.py
      run: |
        cd cocotb/caravel_cocotb/CI
        python3 main.py