name: Cocotb CI

on:
  push:
    branches:
      - main  
      - dev
      - CI_dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Navigate to caravel_cocotb directory
      run: cd root/cocotb/caravel_cocotb

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run cocotb_ci.py
      run: python CI/cocotb_ci.py